import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function run() {
    console.log("---- Iniciando Simulación del Agente (OpenClaw + N8N) ----\n");

    // Get the default Prime Festival event
    const event = await prisma.event.findFirst({
        where: { name: { contains: "Prime" } }
    }) || await prisma.event.findFirst();

    if (!event) {
        console.log("❌ No se encontró el proyecto Prime Festival en la base de datos.");
        return;
    }

    // Realistic data generated by OpenClaw from Ecuador
    const leads = [
        { name: "Conservatorio Superior Nacional de Música", city: "Quito", website: "https://www.consmq.edu.ec/", contactEmail: "info@consmq.edu.ec", contactPhone: "02-222-3333", socialUrl: "https://facebook.com/consmq" },
        { name: "Danzas Jazz Producciones", city: "Guayaquil", socialUrl: "https://instagram.com/danzasjazz", contactPhone: "0991234567" },
        { name: "Academia de Música Chopin", city: "Guayaquil", socialUrl: "https://facebook.com/chopingye", contactEmail: "chopin.gye@ejemplo.com" },
        { name: "Teatro Sánchez Aguilar - Escuela", city: "Samborondón", website: "https://teatrosanchezaguilar.org", socialUrl: "https://instagram.com/tsanchezaguilar" },
        { name: "Borkis Entertainment", city: "Guayaquil", website: "https://borkis.com", contactPhone: "0997654321", socialUrl: "https://instagram.com/borkise" },
        { name: "Conservatorio Antonio Neumane", city: "Guayaquil", contactEmail: "secretaria@neumane.edu.ec" },
        { name: "Sociedad Femenina de Cultura (Centro de Arte)", city: "Guayaquil", website: "https://teatrocentrodearte.org" }
    ];

    console.log(`📡 OpenClaw detectó ${leads.length} instituciones talentosas para participar...\n`);

    for (const lead of leads) {
        const payload = {
            ...lead,
            eventId: event.id,
            type: "INSTITUCION",
            source: "OpenClaw via n8n",
        };

        console.log(`🤖 n8n enviando Webhook (POST) -> ${lead.name}`);

        // Simulate n8n hitting webhook via direct fetch
        await fetch("http://localhost:3001/api/webhooks/marketing/leads", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer prime-marketing-123"
            },
            body: JSON.stringify(payload)
        });
    }

    console.log("\n✅ Base de datos alimentada.");

    // Simulate operational follow-up
    console.log("\n⏩ ... Simulando el paso a paso operacional (Seguimiento automático)\n");
    console.log("n8n procesa la lista y usa Vapi para llamar automáticamente a las academias.\n");

    const borkis = await prisma.participant.findFirst({ where: { name: "Borkis Entertainment" } });
    if (borkis) {
        console.log(`📞 Vapi conversa con Borkis Entertainment. El Director está muy interesado.`);
        console.log(`🤖 n8n envía Webhook (PUT) para actualizar el estado del prospecto...`);

        await fetch(`http://localhost:3001/api/webhooks/marketing/leads/${borkis.id}`, {
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer prime-marketing-123"
            },
            body: JSON.stringify({
                stage: "REUNION_PROGRAMADA",
                notes: "Llamada vía Vapi respondida. Jorge está muy interesado en enviar a sus top 3 cantantes al casting del Prime Festival. Reunión agendada para el jueves 15 con el equipo de EventosPrime.",
                contactName: "Jorge Awad"
            })
        });
        console.log("✅ Borkis Entertainment actualizado a 'REUNION_PROGRAMADA' exitosamente.");
    }

    console.log("\n✨ Simulación completada. Por favor, revisa el Dashboard en la sección de Leads.");
}

run().catch(console.error);
